### ISSUE TITLE
Compiling latest Ifcopenshell v0.7.0 on windows -> IfcPythonPYTHON_wrap.cxx.obj : error LNK2001

### ISSUE THREAD

**Issue by Krande** [IfcOpenShell/IfcOpenShell#1949]
Hi,

I am experimenting (and learning) how to compile Ifcopenshell from the latest master-branch using cmake on github actions using conda-build for different os'es. 

And when trying to compile for windows, it seems like I consistently get the same error message:

When using NMake
```
[ 98%] Linking CXX shared module _ifcopenshell_wrapper.pyd
..
IfcPythonPYTHON_wrap.cxx.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
   Creating library _ifcopenshell_wrapper.lib and object _ifcopenshell_wrapper.exp
IfcPythonPYTHON_wrap.cxx.obj : error LNK2001: unresolved external symbol "public: class H5::IdComponent & __cdecl H5::IdComponent::operator=(class H5::IdComponent const &)" (??4IdComponent@H5@@QEAAAEAV01@AEBV01@@Z)
```

When using Ninja
```
[137/138] Linking CXX shared module ifcwrap\_ifcopenshell_wrapper.pyd
FAILED: ifcwrap/_ifcopenshell_wrapper.pyd 
...
IfcPythonPYTHON_wrap.cxx.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
   Creating library ifcwrap\_ifcopenshell_wrapper.lib and object ifcwrap\_ifcopenshell_wrapper.exp
IfcPythonPYTHON_wrap.cxx.obj : error LNK2001: unresolved external symbol "public: class H5::IdComponent & __cdecl H5::IdComponent::operator=(class H5::IdComponent const &)" (??4IdComponent@H5@@QEAAAEAV01@AEBV01@@Z)
```

I have tried a lot of variations in the process, but here is an example of my cmake build configs:

```
mkdir build && cd build

cmake -G "Ninja" ^
 -D CMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
 -D CMAKE_BUILD_TYPE=Release ^
 -D CMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -D CMAKE_SYSTEM_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -D Python3_FIND_STRATEGY=LOCATION ^
 -D Python3_FIND_REGISTRY=NEVER ^
 -D OCC_INCLUDE_DIR="%LIBRARY_PREFIX%\include\opencascade" ^
 -D OCC_LIBRARY_DIR="%LIBRARY_PREFIX%\lib" ^
 -D CGAL_INCLUDE_DIR="%LIBRARY_PREFIX%\include" ^
 -D GMP_LIBRARY_DIR:FILEPATH="%LIBRARY_PREFIX%\lib" ^
 -D MPFR_LIBRARY_DIR:FILEPATH="%LIBRARY_PREFIX%\lib" ^
 -D HDF5_INCLUDE_DIR:FILEPATH="%LIBRARY_PREFIX%\include" ^
 -D HDF5_LIBRARY_DIR:FILEPATH="%LIBRARY_PREFIX%\lib" ^
 -D COLLADA_SUPPORT=OFF ^
 -D BUILD_EXAMPLES=OFF ^
 -D BUILD_GEOMSERVER=ON ^
 -D BUILD_CONVERT=OFF ^
 -D BUILD_IFCPYTHON=ON ^
 -D BUILD_IFCGEOM=ON ^
 -D IFCXML_SUPPORT=ON ^
 -D MSVC_EXTRA_WARNINGS=OFF ^
 %SRC_DIR%/cmake
if errorlevel 1 exit 1

:: Build and install
cmake --build . -- install

if errorlevel 1 exit 1
```

and my meta.yaml file looks like this:

```yaml
{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}
{% set occt_version = "7.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/IfcOpenShell/IfcOpenShell

build:
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja ==1.10.2
    - cmake
    - swig ==4.0.2

  host:
    - python {{ python }}
    - occt =={{ occt_version }}
    - cgal-cpp ==5.3

  run:
    - python
    - occt =={{ occt_version }}
    - lark-parser
    - deepdiff
    - cgal-cpp ==5.3

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

```

An example of this error using github actions is here: https://github.com/Krande/condapackaging/runs/4552522417?check_suite_focus=true#step:5:25307

While I continue to debug this, does anybody have an idea what could be generating this error and\or point me in the right direction for solving this?

Best Regards
Kristoffer (c++ n00b)
